# Generated by Django 5.0.4 on 2024-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0004_alter_pedido_comuna_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasComuna',
            fields=[
                ('comuna_envio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'view_ventas_comunas',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='iva',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_documento',
            field=models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], default='boleta', help_text="Tipo de documento: 'boleta', 'factura'.", max_length=20),
        ),
    ]
