# Generated by Django 5.0.4 on 2024-08-03 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0006_usuario_ciudad_empresa_usuario_comuna_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='comuna_envio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='comuna_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='giro_comercial',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut_empresa',
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_boleta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='cerveceria.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cod_comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cerveceria.comuna'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=20)),
                ('giro_comercial', models.CharField(max_length=255)),
                ('direccion_empresa', models.CharField(max_length=255)),
                ('numero_empresa', models.CharField(max_length=20)),
                ('comuna_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cerveceria.comuna')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='cerveceria.region'),
        ),
    ]
