# Generated by Django 4.0.6 on 2024-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0007_ciudad_region_remove_detalle_pedido_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.IntegerField(default=0),
        ),
    ]
