# Generated by Django 4.0.6 on 2024-08-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0008_pedido_costo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cerveceria.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='region_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cerveceria.region'),
        ),
        migrations.AlterModelTable(
            name='pedidoentregado',
            table='view_pedidos_despachados',
        ),
    ]
