# Generated by Django 4.0.6 on 2024-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0009_empresa_ciudad_empresa_empresa_region_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_neto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
